### ISSUE TITLE
Chalk detects console as 16colors/basic colors only

### ISSUE THREAD

**Issue by JestDotty** [amejia1/atom-xterm#9]
not sure what's going on here. The tab is called `256color`

also xtreme can't seem to display grey. It just displays white.

I am on windows 8.1 if it is relevant

if I force chalk to user more colors the console messes up the colors (ie, background color + color but randomly) or just doesn't do them.

**Comment by amejia1** [comment]
Noting here, this is due to the use of the 'name' parameter for node-pty. Though it's meant for setting the term type on POSIX systems, it doesn't do anything for Windows.

**Comment by amejia1** [comment]
I tried chalk out in the latest atom-xterm with xterm.js v3 on my Windows machine. Chalk works. See below.

<img width="1920" alt="chalk-in-atom-xterm-demo" src="https://user-images.githubusercontent.com/86134/35190237-c50bc94e-fe2a-11e7-8019-27fb8b25296b.png">

Earlier issues in chalk might very well have been due to the older xterm.js. Going to mark as resolved now that xterm.js v3 is being used.
